"""Validator Agent — evaluates code accuracy and correctness using LLM."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .base_agent import BaseAgent

OUTPUT_ROOT = Path(__file__).parent.parent / "output_projects"

SYSTEM_PROMPT = """You are the Validator Agent in an autonomous AI software-generation pipeline.

You receive a set of implementation tasks, the target architecture, and the actual code generated by the Coder.
Your job is to evaluate whether the generated code accurately and correctly implements the tasks and architecture.

Required JSON shape — return ONLY this object:
{
  "is_accurate": true or false,
  "issues": ["<issue 1>", "<issue 2>"],
  "summary": "<short summary of the validation>"
}

Rules:
- Be strict but fair. If the code completely ignores the task or contains obvious syntax/logic errors, is_accurate should be false.
- If it's generally correct and fulfills the task, is_accurate should be true (you can still list minor issues).
- The 'issues' list will be passed to the RecoveryAgent to fix the code, so be specific about what needs fixing.
"""

class ValidatorAgent(BaseAgent):
    name = "validator"

    async def execute(self, run_id: str, **kwargs: Any) -> dict[str, Any]:
        run = self.state.get(run_id)
        if run is None:
            raise RuntimeError(f"unknown run_id={run_id}")

        out_dir = OUTPUT_ROOT / run_id
        if not out_dir.exists():
            return {"summary": "no output directory to validate"}

        self.log(run_id, "validating generated code...", level="info")

        all_issues = []
        all_accurate = True
        
        # Gather context
        arch = run.architecture or {}

        # Validate each task's generated code
        for task in run.tasks:
            files_content = {}
            
            # Read code files
            for rel_path in task.code_file_paths:
                file_path = OUTPUT_ROOT.parent / rel_path
                if file_path.exists():
                    files_content[rel_path] = file_path.read_text(encoding="utf-8")

            # Read test file
            if task.test_file_path:
                test_path = OUTPUT_ROOT.parent / task.test_file_path
                if test_path.exists():
                    files_content[task.test_file_path] = test_path.read_text(encoding="utf-8")

            if not files_content:
                continue

            payload = {
                "task": {
                    "id": task.id,
                    "title": task.title,
                    "detail": task.detail,
                },
                "architecture": arch,
                "generated_files": files_content
            }

            user_prompt = f"Please validate the following generated code for this task:\n\n```json\n{json.dumps(payload, indent=2)}\n```"

            result = await self.call_groq_json(
                run_id=run_id,
                system_prompt=SYSTEM_PROMPT,
                user_prompt=user_prompt
            )

            is_accurate = result.get("is_accurate", False)
            issues = result.get("issues", [])
            
            if not is_accurate:
                all_accurate = False
            
            if issues:
                all_issues.extend([f"[Task: {task.title}] {issue}" for issue in issues])

        # Run tests locally if tests directory exists
        import subprocess
        pytest_output_str = ""
        tests_dir = out_dir / "tests"
        if tests_dir.exists():
            py_tests = list(tests_dir.rglob("*.py"))
            js_tests = list(tests_dir.rglob("*.js")) + list(tests_dir.rglob("*.jsx"))
            
            if py_tests:
                self.log(run_id, "running pytest execution suite...", level="info")
                try:
                    # Run pytest and capture output
                    proc = subprocess.run(
                        ["pytest", str(tests_dir), "-v"],
                        capture_output=True,
                        text=True,
                        cwd=str(out_dir)
                    )
                    pytest_output_str = f"=== Pytest Execution ===\n{proc.stdout}\n{proc.stderr}\n\n"
                    if proc.returncode != 0:
                        all_accurate = False
                        all_issues.append("[Pytest] Tests failed. See output above.")
                except Exception as e:
                    pytest_output_str = f"=== Pytest Execution ===\nFailed to run pytest: {str(e)}\n\n"
                    all_accurate = False
                    all_issues.append(f"[Pytest] Exception during test execution: {str(e)}")
            elif js_tests:
                self.log(run_id, "running jest execution suite...", level="info")
                try:
                    # Run jest and capture output
                    proc = subprocess.run(
                        ["npx", "--yes", "jest", "--passWithNoTests"],
                        capture_output=True,
                        text=True,
                        cwd=str(out_dir),
                        shell=True
                    )
                    pytest_output_str = f"=== Jest Execution ===\n{proc.stdout}\n{proc.stderr}\n\n"
                    if proc.returncode != 0:
                        all_accurate = False
                        all_issues.append("[Jest] Tests failed. See output above.")
                except Exception as e:
                    pytest_output_str = f"=== Jest Execution ===\nFailed to run jest: {str(e)}\n\n"
                    all_accurate = False
                    all_issues.append(f"[Jest] Exception during test execution: {str(e)}")
            else:
                pytest_output_str = "No Python or JS test files found to execute.\n\n"

        output_str = pytest_output_str + "=== LLM Validation ===\n" + ("\n".join(all_issues) if all_issues else "No issues found. Code is accurate.")

        self.state.set_test_results(run_id, {
            "passed": all_accurate,
            "output": output_str
        })

        if all_accurate:
            summary = "validation passed successfully"
            self.log(run_id, summary, level="success")
            return {"summary": summary}
        else:
            summary = "validation failed with issues"
            self.log(run_id, summary, level="error")
            return {"summary": summary}

